config/routes.rb
Rails.application.routes.draw do
  resources :posts, except: [:index] do
    member do
      post 'like'
      delete 'unlike'
    end
  end

  get 'account/edit'
  get 'account/show'
  patch 'account/update'

  ActiveAdmin.routes(self)
  root 'welcome#index'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  photo       :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ActiveRecord::Base
  validates :photo, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :post_likes, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  mount_uploader :photo, PhotoUploader

  def liked_by_user?(user)
    post_likes.find_by(user: user)
  end

  def like_status
    result = post_likes.limit(3).collect{|pl| pl.user.username}.join(", ")
    result += " and #{post_likes.count - 3} others" if post_likes.count > 3
    result += " likes this"
    return result
  end
end

app/models/post_comment.rb
# == Schema Information
#
# Table name: post_comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  post_id    :integer
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post_like.rb
# == Schema Information
#
# Table name: post_likes
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostLike < ActiveRecord::Base
  validates :user_id, presence: true
  validates :post_id, presence: true
  
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  avatar     :string
#  username   :string
#  name       :string
#  website    :string
#  bio        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  admin      :boolean          default("false")
#

require 'uri'

class User < ActiveRecord::Base

  # Validations
  validates :username, presence: true
  validates :name, presence: true
  # validates :avatar, presence: true
  validates :bio, length: { maximum: 500 }
  validates_format_of :website, :with => URI.regexp, :allow_blank => true

  # Relationships
  has_many :posts, dependent: :destroy
  has_many :post_likes, dependent: :destroy

  # Carrierwave
  mount_uploader :avatar, AvatarUploader

  # Scopes
  scope :admin, -> {where(admin: true)}
  scope :non_admin, -> {where(admin: false)}
  scope :has_website, -> {where("website is not NULL")}
  scope :has_bio, -> {where("bio is not NULL")}


end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to account_edit_path, notice: 'Your account has been updated.'
    else
      render :edit
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :website, :bio, :avatar, :avatar_cache)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def authenticate_admin_user!
    redirect_to root_path if !current_user.admin?
  end

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by(username: 'kjs')
  end

  def signed_in?
    return true if current_user.present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:unlike, :like, :show, :edit, :update, :destroy]
  before_action :authenticate_post, only: [:update, :edit, :destroy]
  
  def like
    #PostLike.where(user: current_user, post: @post).first_or_create

    PostLike.find_or_create_by(user: current_user, post: @post)

    #if PostLike.where(user: current_user, post: @post).count == 0
    #  PostLike.create(user: current_user, post: @post)
    #end

    redirect_to @post
  end

  def unlike
    PostLike.find_by(user: current_user, post: @post).destroy
    redirect_to @post
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy

    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def authenticate_post
      redirect_to root_path if @post.user != current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:photo, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.order('created_at desc').page(params[:page])
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to image_tag("instagram-logo-icon.png", width: '24'), root_path, class: "navbar-brand" %>
    </div>
    <%= link_to "Create Post", new_post_path, class: "btn btn-primary btn-xs navbar-btn" %>

      <% if signed_in? %>
        <p class="navbar-text navbar-right">Signed in as <%= link_to current_user.name, account_edit_path %> <% if current_user.admin? %>| <%= link_to "Admin", admin_root_path %><% end %></p>
      <% end %>
  </div>
</nav>

app/views/layouts/_notices.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:error] %>
  </div>
<% end %>
<% if flash[:warning] %>
  <div class="alert alert-warning"><%= flash[:warning] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render :partial => 'layouts/navbar' %>

  <%= render :partial => 'layouts/notices' %>
  
  <div class="container">
    <%= yield %>
  </div>

  <%= render :partial => 'layouts/footer' %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    

    <%= form_for(@post, :html => {:multipart => true}) do |f| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :photo %><br>
        <%= f.file_field :photo, class: "form-control" %>
        <%= f.hidden_field :photo_cache %>
      </div>
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="actions">
        <%= f.submit "Upload", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <div class="col-md-3">
  </div>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="col-md-3 text-right">
    <ul>
      <li><%= image_tag post.user.avatar.thumb.url, class: "user_avatar" %></li>
      <li>
        <strong><%= post.user.username %></strong><br>
        <%= time_ago_in_words(post.created_at) %> ago
      </li>
    </ul>
  </div>
  <div class="col-md-6" style="width:510px;">
    <div>
      <%= link_to image_tag(post.photo.feed.url), post %>
    </div>
    <%= post.description %><br>
    <% if post.liked_by_user?(current_user) %>
      <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
      <%= form_tag(unlike_post_path(post), method: 'delete') do %>
        <%= submit_tag "Unlike" %>
      <% end %>
    <% else %>
      <%= form_tag like_post_path(post) do %>
        <%= submit_tag "Like" %>
      <% end %>
    <% end %>
    <%= post.like_status %>

    <div class="well well-sm" style="width:510px;">
      <% post.post_comments.each do |comment| %>
        <div>
          <%= image_tag comment.user.avatar.thumb.url, width: '20' %>
          <strong><%= comment.user.username %></strong>
          <%= comment.body %>
        </div>
      <% end %>

    </div>
  </div>
  <div class="col-md-3">
  </div>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Post</h1>
  </div>
  <div class="col-md-3">
  </div>
</div>


<%= render 'form' %>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Create Post</h1>
  </div>
  <div class="col-md-3">
  </div>
</div>


<%= render 'form' %>

app/views/posts/show.html.erb
<%= render :partial => 'posts/post', locals: {post: @post} %>


<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">
    <% if @post.user == current_user %>
      <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-md-3">
  </div>
</div>

app/views/welcome/index.html.erb
<% @posts.each do |post| %>
  <%= render :partial => 'posts/post', locals: {post: post} %>
<% end %>

<div class="row">
  <div class="col-md-3 text-right">
  </div>
  <div class="col-md-6 text-center">
    <%= link_to_next_page @posts, 'Load More', class: "btn btn-primary" %>
  </div>
  <div class="col-md-3">
  </div>
</div>